stages:
    - test
    - deploy
    - diff

test_unit:
    stage: test
    image: dockerlennyy/blog_php
    before_script: 
        - composer install
    script: bin/phpunit

heroku:
    stage: deploy
    image: ruby
    before_script:
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_STAGING_API_KEY
    only: 
        - master
    when: on_success

hadolint:
    stage: diff
    image: hadolint/hadolint
    script:
        - hadolint Dockerfile
