name: Tests

on: [push_request]

jobs:
  hadolint:
    name: Check docker images (Hadolint)
    runs-on: ubuntu-latest
    container: hadolint/hadolint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Checking image Best Practices
        run: hadolint Dockerfile

  test_unit:
    name: test
    runs-on: ubuntu-latest
    container: tlacheheb/blog_php
    steps:
      - name: install composer package
        run: composer install
      - name: start test
        run: bin/phpunit