name: Tests

on: [push]

jobs:
  hadolint:
    name: Check docker images (Hadolint)
    runs-on: ubuntu-latest
    container: hadolint/hadolint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Checking image Best Practices
        run: hadolint Dockerfile

  test_unit:
    name: test
    runs-on: ubuntu-latest
    container: tlacheheb/blog_php
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: install composer package
        run: composer install
      - name: start test
        run: bin/phpunit
  
  hadolint:
    name: deploy
    container: ruby
    runs-on: ubuntu-latest
    steps:
      - name: install dpl
        run: gem install dpl
      - name: start dpl
        run: dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_STAGING_API_KEY